title: "Anastasia-Olga (Olnancy) Tzirides"
description: "Learning Scientist | GenAI in Education | Learning Design & Educational Technology"
url: "https://olnancy.github.io"
baseurl: ""

remote_theme: "academicpages/academicpages.github.io"
minimal_mistakes_skin: "default"

markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

author:
  name   : "Anastasia-Olga (Olnancy) Tzirides"
  bio    : "Learning Scientist | GenAI in Education | Learning Design & Educational Technology"
  avatar : "/images/Tzirides_2024.jpg"
  location: "United States"
  employer: "University of Illinois"
  email  : "aotzirides@gmail.com"
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=7VeZ2T8AAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anastasia-olga-olnancy-tzirides/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-8641-206X"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:aotzirides@gmail.com"

resume_url: "/assets/files/CV_EdTech_Jan2026.pdf"
cv_url: "/assets/files/Tzirides_CV_Academic_20Jan26.pdf"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      toc: false
